version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: x64
shallow_clone: true
clone_depth: 1
before_build:
- cmd: >-
    echo #pragma once > Version.h

    echo #define DE_VERSION %APPVEYOR_BUILD_NUMBER% >> Version.h

    echo #define DE_VERSIONSTR "%APPVEYOR_BUILD_NUMBER%" >> Version.h
build:
  project: DisruptEditor.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: 7z a DisruptEditor.zip %APPVEYOR_BUILD_FOLDER%/x64/Release/*.exe %APPVEYOR_BUILD_FOLDER%/x64/Release/*.dll %APPVEYOR_BUILD_FOLDER%/DisruptEditor/res %APPVEYOR_BUILD_FOLDER%/Readme.md
artifacts:
- path: DisruptEditor.zip
- path: x64/Release/*.pdb
